#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#include "simulator.h"



void ShowInstructions()
{
    int choice;

    printf("\n===== VIEW INSTRUCTIONS =====\n");

    printf("This program simulates a naval battle between a Battleship B and Escort Ships E.\n\n");

    printf("1. Start Simulation\n");
    printf("   - Enter the battlefield size and number of Escort Ships.\n");
    printf("   - Enter the required Battleship information.\n");
    printf("   - Escort Ship properties are generated by the program.\n\n");

    printf("2. Part 1 Simulations\n");
    printf("   - Part 1-A performs the basic naval battle simulation.\n");
    printf("   - Part 1-B simulates Battleship movement and gun jamming.\n");
    printf("   - Part 1-C introduces cumulative impact damage to the Battleship.\n\n");

    printf("3. Part 2 Simulations\n");
    printf("   - Part 2-A introduces Battleship firing delay and attack order.\n");
    printf("   - Part 2-B allows Escort Ships to fire continuously.\n");
    printf("   - Part 2-C introduces impact power degradation after repeated firing.\n\n");

    printf("4. Simulation Results\n");
    printf("   - Results are saved in text files.\n");
    printf("   - Select Simulation Statistics from the Main Menu to view results.\n\n");

    printf("5. Exit\n");
    printf("   - Select Exit from the Main Menu to close the simulator.\n");

    printf("\nEnter 1 to return to Main Menu: ");
    scanf("%d", &choice);
}



void ShowStatistics()
{
    FILE *file = NULL;
    char line[300];
    int choice;

    printf("\n===== SIMULATION STATISTICS =====\n");

    printf("1. Initial Conditions\n");
    printf("2. Final Conditions\n");
    printf("3. Hit Details\n");

    printf("\n--- PART 1 ---\n");
    printf("4. Part 1-B Simulation 1\n");
    printf("5. Part 1-B Simulation 2\n");
    printf("6. Part 1-C Results\n");
    printf("7. Part 1-C Path Results\n");

    printf("\n--- PART 2-A ---\n");
    printf("8. Part 2-A Results\n");
    printf("9. Part 2-A Path Results\n");
    printf("10. Part 2-A Part 1-C Results\n");
    printf("11. Part 2-A Jam Results\n");

    printf("\n--- PART 2-B ---\n");
    printf("12. Part 2-B Results\n");
    printf("13. Part 2-B Path Results\n");
    printf("14. Part 2-B Jam Results\n");

    printf("\n--- PART 2-C ---\n");
    printf("15. Part 2-C Results\n");

    printf("\n16. Return to Main Menu\n");

    printf("\nEnter choice: ");
    scanf("%d", &choice);

    if (choice == 1)
    {
        file = fopen("initial_conditions.txt", "r");
    }
    else if (choice == 2)
    {
        file = fopen("final_conditions.txt", "r");
    }
    else if (choice == 3)
    {
        file = fopen("hit_details.txt", "r");
    }
    else if (choice == 4)
    {
        file = fopen("part1b_simulation1.txt", "r");
    }
    else if (choice == 5)
    {
        file = fopen("part1b_simulation2.txt", "r");
    }
    else if (choice == 6)
    {
        file = fopen("part1c_results.txt", "r");
    }
    else if (choice == 7)
    {
        file = fopen("part1c_path_results.txt", "r");
    }
    else if (choice == 8)
    {
        file = fopen("part2a_results.txt", "r");
    }
    else if (choice == 9)
    {
        file = fopen("part2a_path_results.txt", "r");
    }
    else if (choice == 10)
    {
        file = fopen("part2a_part1c_results.txt", "r");
    }
    else if (choice == 11)
    {
        file = fopen("part2a_jam_results.txt", "r");
    }
    else if (choice == 12)
    {
        file = fopen("part2b_results.txt", "r");
    }
    else if (choice == 13)
    {
        file = fopen("part2b_path_results.txt", "r");
    }
    else if (choice == 14)
    {
        file = fopen("part2b_jam_results.txt", "r");
    }
    else if (choice == 15)
    {
        file = fopen("part2c_results.txt", "r");
    }
    else if (choice == 16)
    {
        return;
    }
    else
    {
        printf("Invalid choice.\n");
        return;
    }

    if (file == NULL)
    {
        printf("\nNo saved result found. Run the simulation first.\n");
        return;
    }

    printf("\n===== SAVED SIMULATION RESULT =====\n\n");

    while (fgets(line, sizeof(line), file) != NULL)
    {
        printf("%s", line);
    }

    fclose(file);

    printf("\n===================================\n");
}







int main()
{
    int choice;

    while (1)
    {
        printf("\n===== ADVANCED NAVAL BATTLE SIMULATOR =====\n");
        printf("1. Start Simulation\n");
        printf("2. View Instructions\n");
        printf("3. Simulation Statistics\n");
        printf("4. Set Random Seed\n");
        printf("5. Exit\n");

        printf("Enter your choice: ");
        scanf("%d", &choice);

        if (choice == 2)
        {
            ShowInstructions();
            continue;
        }
        else if (choice == 3)
        {
            ShowStatistics();
            continue;
        }
        else if (choice == 4)
        {
            int seed;

            printf("Enter random seed: ");
            scanf("%d", &seed);

            srand(seed);

            printf("Random seed set to %d\n", seed);
            continue;
        }
        else if (choice == 5)
        {
            printf("\nExiting program...\n");
            return 0;
        }
        else if (choice != 1)
        {
            printf("\nInvalid choice. Please enter 1 - 5.\n");
            continue;
        }

        printf("\n===== STARTING SIMULATION =====\n");







    int d;
    int n;
    int k;
    int t;
    float thetaMin;
    float firingDelay;

    BattleShip battleship;

    EscortShip escorts[MAX_ESCORTS];
    EscortShip escortsPart1C[MAX_ESCORTS];
    EscortShip escortsSimulation2[MAX_ESCORTS];
    EscortShip escortsPart2A[MAX_ESCORTS];    EscortShip escortsInitial[MAX_ESCORTS];
    EscortShip escortsPart2AC[MAX_ESCORTS];
    EscortShip escortsPart2B[MAX_ESCORTS];
    EscortShip escortsPart2BPath[MAX_ESCORTS];
    EscortShip escortsPart2C[MAX_ESCORTS];
    EscortShip escortsPart2AJam[MAX_ESCORTS];
    EscortShip escortsPart2BJam[MAX_ESCORTS];


    srand(time(NULL));

    printf("=====================================\n");
    printf("     ADVANCED NAVAL BATTLE SIMULATOR\n");
    printf("=====================================\n");

    printf("\nEnter battlefield size D: ");
    scanf("%d", &d);

    printf("Enter number of escort ships: ");
    scanf("%d", &n);

    printf("Enter number of battleship path positions: ");
    scanf("%d", &k);

printf("Enter iteration when battleship gun gets jammed: ");
scanf("%d", &t);

printf("Enter minimum vertical angle after gun jam: ");
scanf("%f", &thetaMin);

printf("Enter Battleship gun firing delay (seconds): ");
scanf("%f", &firingDelay);

if (t <= 0 || t >= k)
{
    printf("Invalid jam iteration. t must be between 1 and k-1.\n");
    return 1;
}

if (thetaMin <= 0 || thetaMin >= 30)
{
    printf("Invalid minimum angle. Angle must be between 0 and 30 degrees.\n");
    return 1;
}


    if (n > MAX_ESCORTS)
    {
        printf("Maximum escort ships allowed: %d\n",
               MAX_ESCORTS);

        return 1;
    }

    setupBattleShip(&battleship, d);

    setupEscortShips(
        escorts,
        n,
        d,
        battleship.maxVelocity
    );

/* Keep original escort conditions */
for (int i = 0; i < n; i++)
{
    escortsInitial[i] = escorts[i];
}

    displayBattlefield(
        battleship,
        escorts,
        n
    );


saveInitialConditions(
    battleship,
    escorts,
    n,
    d
);

simulatePart1A(
    &battleship,
    escorts,
    n
);

for (int i = 0; i < n; i++)
{
    escortsSimulation2[i] = escorts[i];
}

simulatePart1B(
    &battleship,
    escorts,
    n,
    d,
    k
);

simulatePart1B2(
    &battleship,
    escortsSimulation2,
    n,
    d,
    k,
    t,
    thetaMin
);

for (int i = 0; i < n; i++)
{
    escortsPart1C[i] = escortsSimulation2[i];
}

simulatePart1C(
    &battleship,
    escortsPart1C,
    n
);

for (int i = 0; i < n; i++)
{
    escortsPart1C[i] = escortsSimulation2[i];
}

simulatePart1CPath(
    &battleship,
    escortsPart1C,
    n,
    d,
    k
);

/* Fresh copy for Part 2-A */
for (int i = 0; i < n; i++)
{
    escortsPart2A[i] = escortsInitial[i];
}

/* Part 2-A single position simulation */
simulatePart2A(
    &battleship,
    escortsPart2A,
    n,
    firingDelay
);

/* Reset escorts before Part 2-A path simulation */
for (int i = 0; i < n; i++)
{
    escortsPart2A[i] = escortsInitial[i];
}

/* Part 2-A path simulation */
simulatePart2APath(
    &battleship,
    escortsPart2A,
    n,
    d,
    k,
    firingDelay
);

/* Fresh escort copy for Part 2-A / Part 1-C */
for (int i = 0; i < n; i++)
{
    escortsPart2AC[i] = escortsInitial[i];
}

simulatePart2AC(
    &battleship,
    escortsPart2AC,
    n,
    firingDelay
);

/* Fresh escort copy for Part 2-B */
for (int i = 0; i < n; i++)
{
    escortsPart2B[i] = escortsInitial[i];
}

simulatePart2B(
    &battleship,
    escortsPart2B,
    n,
    firingDelay
);

/* Fresh escort copy for Part 2-B path simulation */
for (int i = 0; i < n; i++)
{
    escortsPart2BPath[i] = escortsInitial[i];
}

simulatePart2BPath(
    &battleship,
    escortsPart2BPath,
    n,
    d,
    k,
    firingDelay
);





/* Fresh escort copy for Part 2-A jam simulation */
for (int i = 0; i < n; i++)
{
    escortsPart2AJam[i] = escortsInitial[i];
}

simulatePart2AJam(
    &battleship,
    escortsPart2AJam,
    n,
    d,
    k,
    t,
    thetaMin,
    firingDelay
);


/* Fresh escort copy for Part 2-B jam simulation */
for (int i = 0; i < n; i++)
{
    escortsPart2BJam[i] = escortsInitial[i];
}

simulatePart2BJam(
    &battleship,
    escortsPart2BJam,
    n,
    d,
    k,
    t,
    thetaMin,
    firingDelay
);







/* Fresh escort copy for Part 2-C */
for (int i = 0; i < n; i++)
{
    escortsPart2C[i] = escortsInitial[i];
}

simulatePart2C(
    &battleship,
    escortsPart2C,
    n,
    firingDelay
);

printf("\nSimulation completed successfully.\n");
printf("Returning to Main Menu...\n");

    }
}
